### PR TITLE
Added easy-firestore to the made in Senegal collection

### PR DESCRIPTION
**Pull request by Alkaly02**

### CODE REVIEW

**Review by MedouneSGB — APPROVED** [review]
LGTM🔥

**Comment by Alkaly02** [comment]
LGTM veut dire quoi?😅

**Comment by daoodaba975** [comment]
> LGTM veut dire quoi?😅

Looks Good To Me 😁

**Comment by daoodaba975** [comment]
Good job @Alkaly02 thx for the contribution ✨

**Pull request merged**
