### PR TITLE
Add github user stats project

### PR DESCRIPTION
**Pull request by bambadiagne**
With this tool, you will be able to know for example who uses a certain language (go, python, java,...), retrieve all users from a location for your dataset for example, it can also help recruiters...

### CODE REVIEW

**Review by ManuSquall — APPROVED** [review]
LGTM! Thanks 🥳🥳

Just wondering which coming first in alphabetical order between "Github User Stats"  and " Git Jafewoul"? (not sure 😅)

**Review by MedouneSGB — CHANGES_REQUESTED** [review]
Move to line 109
Alphabétiquement **Git Jafewoul** devrait venir avant **Github User Stats**.

**Comment by bambadiagne** [comment]
> Move to line 109 Alphabétiquement **Git Jafewoul** devrait venir avant **Github User Stats**.

It's done master

**Review by MedouneSGB — APPROVED** [review]
LGTM 🚀✨

**Review by ManuSquall — APPROVED** [review]
LGTM!

**Pull request merged**
